### PR TITLE
Fix/cjs import base64 arraybuffer

### PR DESCRIPTION
**Pull request by oxidia**
[issue link](https://github.com/regulaforensics/FaceSDK-web-js-client/issues/21)

### CODE REVIEW

**Comment by oxidia** [comment]
@hleb-albau can you please have a look at this?

**Comment by hleb-albau** [comment]
@ivan-gil @ikliashchou 
could you please assist here, js is not my main language

@oxidia sorry for late reply, in review

**Comment by oxidia** [comment]
@hleb-albau Thank you 🙏

**Review by ivan-gil — CHANGES_REQUESTED** [review]
ci/cd pipeline failed. would you be so kind to check  error and fix it

**Comment by oxidia** [comment]
Hello @ivan-gil, thank you for your response
I am not so familiar with GitHub actions, my suggestion is to keep it simple, and just test the esm part of the examples!
Can you please confirm?
so my fix is as follow
```diff
name: run smoke test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm install
-       working-directory: ./example
+       working-directory: ./example/esm
      - run: node --unhandled-rejections=strict index.js
-       working-directory: ./example
+       working-directory: ./example/esm
        env:
          API_BASE_PATH: "https://test-faceapi.regulaforensics.com"

```

**Comment by ivan-gil** [comment]
>

**Comment by ivan-gil** [comment]
> Hello @ivan-gil, thank you for your response I am not so familiar with GitHub actions, my suggestion is to keep it simple, and just test the esm part of the examples! Can you please confirm? so my fix is as follow
> 
> ```diff
> name: run smoke test
> 
> on:
>   push:
>     branches:
>       - master
>   pull_request:
>     branches:
>       - master
> 
> jobs:
>   run_smoke_test:
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@v2
>       - uses: actions/setup-node@v1
>         with:
>           node-version: 14
>           registry-url: https://registry.npmjs.org/
>       - run: npm install
>       - run: npm run build
>       - run: npm install
> -       working-directory: ./example
> +       working-directory: ./example/esm
>       - run: node --unhandled-rejections=strict index.js
> -       working-directory: ./example
> +       working-directory: ./example/esm
>         env:
>           API_BASE_PATH: "https://test-faceapi.regulaforensics.com"
> ```

Before you changes tests were run upon both esm and cjs environments as there was one index js. So for github action we should run test twice both for esm and cjs types of modules. I will extends PR soon and we can merge it

**Comment by oxidia** [comment]
> > Hello @ivan-gil, thank you for your response I am not so familiar with GitHub actions, my suggestion is to keep it simple, and just test the esm part of the examples! Can you please confirm? so my fix is as follow
> > ```diff
> > name: run smoke test
> > 
> > on:
> >   push:
> >     branches:
> >       - master
> >   pull_request:
> >     branches:
> >       - master
> > 
> > jobs:
> >   run_smoke_test:
> >     runs-on: ubuntu-latest
> >     steps:
> >       - uses: actions/checkout@v2
> >       - uses: actions/setup-node@v1
> >         with:
> >           node-version: 14
> >           registry-url: https://registry.npmjs.org/
> >       - run: npm install
> >       - run: npm run build
> >       - run: npm install
> > -       working-directory: ./example
> > +       working-directory: ./example/esm
> >       - run: node --unhandled-rejections=strict index.js
> > -       working-directory: ./example
> > +       working-directory: ./example/esm
> >         env:
> >           API_BASE_PATH: "https://test-faceapi.regulaforensics.com"
> > ```
> 
> Before you changes tests were run upon both esm and cjs environments as there was one index js. So for github action we should run test twice both for esm and cjs types of modules. I will extends PR soon and we can merge it

I didn't quite understand what should I do next, can you please put more details on this.

**Pull request closed without merging**
